In [6]:
import numpy as np
import pandas as pd

In [7]:
test = pd.DataFrame(
    [
        [1,1,1,1,1,1,1,1,1,1,],
        [1,1,1,1,1,1,1,0,0,1,],
        [1,1,1,1,1,1,1,1,0,1,],
        [1,1,1,1,1,1,1,1,1,1,],
        [1,1,1,1,1,1,1,1,0,1,],
        [1,1,1,1,1,1,1,1,0,1,],
        [1,1,1,1,1,1,1,0,1,1,],
        [0,1,1,0,1,1,0,0,1,1,],
        [1,1,1,1,1,1,1,0,0,1,],
        [1,1,0,1,0,1,1,0,0,1,],
        [0,0,1,1,1,1,1,1,0,1,],
        [1,1,1,0,1,1,1,0,0,0,],
        [1,1,0,1,1,1,0,0,0,1,],
        [0,1,1,0,1,0,1,1,0,0,],
        [0,1,1,0,1,0,1,0,0,1,],
        [1,1,0,0,1,0,1,0,0,0,],
        [1,1,0,1,1,1,0,0,0,0,],
        [0,1,0,0,1,1,0,0,0,0,],
        [0,0,0,0,1,0,1,1,0,1,],
        [0,0,0,0,0,1,0,0,0,1,],
    ],
    columns = ['q'+str(n) for n in range(1,11)],
    index = ['Hasegawa','Honda', 'Uchikawa', 'Matsuda','LaHair','Yanagita','Yoshimura','Yamazaki','Imamiya','Pena','Settu','Yamada','Takeda','Ohtonari',
            'Terahara','Higashihama','Senga','Iwasaki','Morifuku','Falkenborg']
)

In [8]:
test.shape

(20, 10)

In [97]:
class TestTheory:
    def __init__(self, array):
        self.array = array
    def calculate_statistics(self):

        '''
        zscore
        '''
        sums = self.array.sum(axis=1)
        self.zscore = (sums - sums.mean()) /  np.std(sums)
        '''
        偏差値
        '''
        self.hensachi = 10*self.zscore + 50
        

In [98]:
class CTT(TestTheory):
    def fit(self):
        '''
        項目困難度 item difficulty
        '''
        self.item_difficulty = self.array.mean(axis=0)
        '''
        項目識別力 item discriminancy
        '''
        y_mean = self.array.mean(axis=1)   
        item_discriminancy = []
        
        for y in self.array.T:
            item_discriminancy.append(np.corrcoef(y_mean, y)[0][1])
        self.item_discriminancy = np.array(item_discriminancy)
        

In [99]:
ctt = CTT(test.values)

In [100]:
ctt.fit()

In [101]:
ctt.item_difficulty

array([0.65, 0.85, 0.65, 0.6 , 0.9 , 0.8 , 0.75, 0.4 , 0.2 , 0.75])

In [102]:
ctt.item_discriminancy.shape

(10,)

In [103]:
ctt.item_discriminancy

array([0.62784679, 0.40268102, 0.71851059, 0.76795935, 0.36757294,
       0.44324972, 0.53678755, 0.46783731, 0.47568263, 0.48685383])

In [104]:
ctt.calculate_statistics()

In [105]:
ctt.zscore

array([ 1.49191369,  0.62703619,  1.05947494,  1.49191369,  1.05947494,
        1.05947494,  1.05947494, -0.23784131,  0.62703619, -0.23784131,
        0.19459744, -0.23784131, -0.23784131, -0.67028006, -0.67028006,
       -1.10271881, -0.67028006, -1.53515756, -1.10271881, -1.96759631])

In [106]:
ctt.hensachi

array([64.91913688, 56.27036188, 60.59474938, 64.91913688, 60.59474938,
       60.59474938, 60.59474938, 47.62158687, 56.27036188, 47.62158687,
       51.94597438, 47.62158687, 47.62158687, 43.29719937, 43.29719937,
       38.97281187, 43.29719937, 34.64842437, 38.97281187, 30.32403687])